Sarah Ruello/week_05/rodent_app/config/routes.rb
Rails.application.routes.draw do
  
  #index
  get '/rodents' => 'rodents#index'
  
  #new/create
  get '/rodents/new' => 'rodents#new', :as => :new_rodent
  post '/rodents' => 'rodents#create'

  #show
  get '/rodents/:id' => 'rodents#show', :as => :rodent

  #edit/update
  get '/rodents/:id/edit' => 'rodents#edit', :as => :edit_rodent
  post '/rodents/:id' => 'rodents#update'

  #delete
  delete '/rodents/:id' => 'rodents#destroy'

end

Sarah Ruello/week_05/rodent_app/app/models/rodent.rb
class Rodent < ActiveRecord::Base

end    

Sarah Ruello/week_05/rodent_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     skip_before_action :verify_authenticity_token # needed for handwritten POST forms
end

Sarah Ruello/week_05/rodent_app/app/controllers/rodents_controller.rb
class RodentsController < ApplicationController

    def index
        @rodents = Rodent.all
    end        

    def show 
        @rodent = Rodent.find params[:id]
    end    

    def new         
    end    

    def create 
        rodent = Rodent.create :name => params[:name], :family => params[:family], :lifespan => params[:lifespan], :diet => params[:diet], :image => params[:image]
        redirect_to rodent_path(rodent.id) # show page /rodents/23
    end  

    def edit 
        @rodent = Rodent.find params[:id]
    end    

    def update
        rodent = Rodent.find params[:id]
        rodent.name = params[:name]
        rodent.family = params[:family]
        rodent.lifespan = params[:lifespan]
        rodent.diet = params[:diet]
        rodent.image = params[:image]
        rodent.save
        redirect_to rodent_path(rodent.id)
    end

    def destroy 
        rodent = Rodent.find params[:id]
        rodent.destroy
        redirect_to rodents_path
    end   
end    

Sarah Ruello/week_05/rodent_app/app/views/rodents/edit.html.erb
<h1>Edit rodent</h1>


<form action="<%= rodent_path(@rodent.id) %>" method="post">

<label>
<span class="label-name">Name:</span>
<input type="text" name="name" required value="<%=@rodent.name%>">
</label><br>

<label>
<span class="label-name">Family:</span>
<input type="text" name="family" value="<%=@rodent.family%>">
</label><br>

<label>
<span class="label-name">Lifespan:</span>
<input type="number" name="lifespan" value="<%=@rodent.lifespan%>">
</label><br>

<label>
<span class="label-name">Diet:</span>
<input type="text" name="diet" value="<%=@rodent.diet%>">
</label><br>

<label>
<span class="label-name">Image:</span>
<input type="url" name="image" value="<%=@rodent.image%>">
</label><br>

<button>Submit</button>
</form>

Sarah Ruello/week_05/rodent_app/app/views/rodents/index.html.erb
<center>
<h1>🦫 RodentApp 🐿️</h1>

<p style="font-style: italic; letter-spacing: 2px;">rodents all day, all night</p>
</center>
<% @rodents.each do |rodent| %>
  <p>
  🌱  <%= link_to rodent.name, rodent_path(rodent.id) %>
  </p>
<% end %>

Sarah Ruello/week_05/rodent_app/app/views/rodents/new.html.erb
<h1>New rodent</h1>


<form action="<%= rodents_path %>" method="post">

<label>
<span class="label-name">Name:</span> 
<input type="text" name="name" required>
</label><br>

<label>
<span class="label-name">Family:</span> 
<input type="text" name="family">
</label><br>

<label>
<span class="label-name">Lifespan:</span> 
<input type="number" name="lifespan">
</label><br>

<label>
<span class="label-name">Diet:</span> 
<input type="text" name="diet">
</label><br>

<label>
<span class="label-name">Image:</span> 
<input type="url" name="image">
</label><br>

<button>Submit</button>
</form>

Sarah Ruello/week_05/rodent_app/app/views/rodents/show.html.erb
<h1><%= @rodent.name %></h1>

<%= image_tag @rodent.image, :class => 'feature' if @rodent.image.present? %>

<div class="details">
<ul>
  <li><span class="label-name">Name:</span> <%= @rodent.name %></li>
  <li><span class="label-name">Family:</span> <%= @rodent.family %></li>
  <li><span class="label-name">Lifespan:</span> <%= @rodent.lifespan %> years</li>
  <li><span class="label-name">Diet:</span> <%= @rodent.diet %></li>
</ul>
</div>
<div class="footer">
<%= link_to 'Edit rodent', edit_rodent_path(@rodent.id) %>
<br>
<br>
<%= button_to 'Delete rodent', rodent_path(@rodent.id), :method => 'delete', :class => 'btn'%>
</div>