Aleksandr Kuzmin/rubycountries/config/routes.rb
Rails.application.routes.draw do
root :to => "cities#index"
resources :countries
resources :cities



end

Aleksandr Kuzmin/rubycountries/app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country, :optional => true
end

Aleksandr Kuzmin/rubycountries/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
end

Aleksandr Kuzmin/rubycountries/app/controllers/cities_controller.rb
class CitiesController < ApplicationController

def index
  @cities =City.all
end

def show
  @city = City.find params[:id]
end

def new
@city = City.new
end

def create
city= City.find city_params
  redirect_to city
end







private
def city_params
  params.require(:city).permit(:name,:formation,:image,:country_id)
end

end

Aleksandr Kuzmin/rubycountries/app/controllers/countries_controller.rb
class CountriesController < ApplicationController

def index
    @countries = Country.all
end

def show
    @country = Country.find params[:id]
end


def new
  @country = Country.new
end

def create
  country = Country.create country_params
  redirect_to country
end

def destroy
  country = Country.find params[:id]
  country.destroy
  redirect_to countries_path
end

def edit
  @country= Country.find params[:id]
end

def update
  country = Country.find params[:id]
  country.update country_params
  redirect_to country
end

private
def country_params
  params.require(:country).permit(:name,:capital,:currency,:image,:formation)

end



end

Aleksandr Kuzmin/rubycountries/app/helpers/cities_helper.rb
module CitiesHelper
end

Aleksandr Kuzmin/rubycountries/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Countries</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
    <nav>
      <%= link_to 'All countries', countries_path %>
      <%= link_to 'New country', new_country_path %>

      <%= link_to 'All cities', cities_path %>
      <%= link_to 'New city', new_city_path %>

    </nav>
      <%= yield %>
    </div>

  </body>
</html>