Alex Poulsen/week-05/billionaires_app/config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#index'
  #index
  get '/billionaires' => 'pages#index'

  get '/billionaires/new' => 'pages#new', :as => :new_billionaire

  get '/billionaires/:id' => 'pages#show', :as => :billionaire

  post '/billionaires/:id' => 'pages#update'

  get '/billionaires/:id/edit' => 'pages#edit', :as => :edit_billionaire

  post '/billionaires' => 'pages#create'

  delete '/billionaires/:id' => 'pages#destroy'

end

Alex Poulsen/week-05/billionaires_app/app/models/billionaire.rb
class Billionaire < ActiveRecord::Base
end

Alex Poulsen/week-05/billionaires_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

Alex Poulsen/week-05/billionaires_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @billionaires = Billionaire.all
  end

  def show
    @billionaire = Billionaire.find params[:id]
    @wealth_time = @billionaire.net_worth / 50000
  end

  def new
  end

  def create
    billionaire = Billionaire.create :name => params[:name], :age => params[:age], :residence => params[:residence], :net_worth => params[:net_worth], :hobbies => params[:hobbies]
    redirect_to billionaire_path(billionaire.id)
  end

  def edit
    @billionaire = Billionaire.find params[:id]
  end

  def update
    billionaire = Billionaire.find params[:id]
    billionaire.name = params[:name]
    billionaire.age = params[:age]
    billionaire.residence = params[:residence]
    billionaire.net_worth = params[:net_worth]
    billionaire.hobbies = params[:hobbies]
    billionaire.save

    redirect_to billionaire_path(billionaire.id)
  end

  def destroy
    billionaire = Billionaire.find params[:id]
    billionaire.destroy
    redirect_to billionaires_path
  end

end

Alex Poulsen/week-05/billionaires_app/app/views/pages/edit.html.erb
<h1>Edit Billionaire</h1>

<form action="<%= billionaire_path(@billionaire.id) %>" method='post'>

  <label for="">
    Name:
    <input type="text" name='name' required value="<%= @billionaire.name %>">
  </label>

  <label for="">
    Age:
    <input type="number" name='age' value="<%= @billionaire.age %>">
  </label>

  <label for="">
    Residence
    <input type="text" name='residence' value="<%= @billionaire.residence %>">
  </label>

  <label for="">
    Net Worth:
    <input type="number" name='net_worth' required value="<%= @billionaire.net_worth %>">
  </label>

  <label for="">
    Hobbies:
    <input type="text" name='hobbies' value="<%= @billionaire.hobbies %>">
  </label>

  <button>Edit Billionaire</button>

</form>

Alex Poulsen/week-05/billionaires_app/app/views/pages/index.html.erb
<h1><strike>Evil Personified</strike> Billionaires Index</h1>

<% @billionaires.each do |b| %>
  <p>
    <%= link_to b.name, billionaire_path(b.id) %>
  </p>
  <% end %>

Alex Poulsen/week-05/billionaires_app/app/views/pages/new.html.erb
<h1>New Billionaire Form</h1>
<h3>Don't do this</h3>

<form action="<%= billionaires_path %>" method='post'>

  <label for="">
    Name:
    <input type="text" name='name' required>
  </label>

  <label for="">
    Age:
    <input type="number" name='age'>
  </label>

  <label for="">
    Residence
    <input type="text" name='residence'>
  </label>

  <label for="">
    Net Worth:
    <input type="number" name='net_worth' required>
  </label>

  <label for="">
    Hobbies:
    <input type="text" name='hobbies'>
  </label>

  <button>Create Billionaire</button>

</form>

Alex Poulsen/week-05/billionaires_app/app/views/pages/show.html.erb
<h1><%= @billionaire.name %></h1>

<ul>
  <li>Name: <%= @billionaire.name %></li>
  <li>Age: <%= @billionaire.age %></li>
  <li>Residence: <%= @billionaire.residence %></li>
  <li>Net Worth: <%= number_to_human @billionaire.net_worth %></li>
  <li>Hobbies: <%= @billionaire.hobbies %></li>
</ul>

<h2>Fun Fact</h2>

<p>It would take the average Australian worker <%= number_to_human @wealth_time %> years to acculmulate that wealth</p>

<div class="controls">
  <%= link_to "Edit Billionaire", edit_billionaire_path(@billionaire.id) %>
  <%= button_to "Delete Billionaire", billionaire_path(@billionaire.id), :method => :delete %>
</div>