Keith Ho/week_5/day_3/maroon5/config/routes.rb
Rails.application.routes.draw do
  root :to => "albums#home"
  resources :albums
  resources :songs
end

Keith Ho/week_5/day_3/maroon5/app/models/album.rb
class Album < ActiveRecord::Base
  has_many :songs
end

Keith Ho/week_5/day_3/maroon5/app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album, :optional => true
end

Keith Ho/week_5/day_3/maroon5/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find params[:id]
  end

  def new
    @album = Album.new
  end

  def create
    album = Album.create album_params
    redirect_to album
  end

  def edit
    @album = Album.find params[:id]
  end

  def update
    album = Album.find params[:id]
    album.update album_params
    redirect_to album
  end

  def destroy
    album = Album.find params[:id]
    album.destroy
    redirect_to albums_path
  end

  private
  def album_params
    params.require(:album).permit(:name, :thumbs_up, :released, :image)

  end
end

Keith Ho/week_5/day_3/maroon5/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find params[:id]
  end

  def new
    @song = Song.new
  end

  def create
    song = Song.create song_params
    redirect_to song
  end

  def edit
    @song = Song.find params[:id]
  end

  def update
    song = Song.find params[:id]
    song.update song_params
    redirect_to song
  end

  def destroy
    song = Song.find params[:id]
    song.destroy
    redirect_to songs_path
  end

  private
  def song_params
    params.require(:song).permit(:name, :thumbs_up, :link, :album_id)

  end
end

Keith Ho/week_5/day_3/maroon5/app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
<%= f.label :name %>
<%= f.text_field :name, :required => true %>

<%= f.label :link %>
<%= f.url_field :link %>

<%= f.label :thumbs_up, "Do you like it?" %>
<%= f.check_box :thumbs_up %>

<%= f.label :album_id %>
<%= f.select :album_id, Album.pluck(:name, :id), :include_blank => true %>

<%= f.submit %>
<% end %>

Keith Ho/week_5/day_3/maroon5/app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render :partial => "form" %>

Keith Ho/week_5/day_3/maroon5/app/views/songs/index.html.erb
<h1>All Songs</h1>

<% @songs.each do |song| %>
  <ul class="songs-container">
    <li>
      <%= link_to song.name, song_path(song.id) %>
      <% if song.thumbs_up == true %>
        <span>👍</span>
      <% else %>
        <span>👎</span>
      <% end %>
    </li>
  </ul>
<% end %>

Keith Ho/week_5/day_3/maroon5/app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render :partial => "form" %>

Keith Ho/week_5/day_3/maroon5/app/views/songs/show.html.erb
<h1>
  <%= @song.name %>
  <% if @song.thumbs_up == true %>
    <span>👍</span>
  <% else %>
    <span>👎</span>
  <% end %>
</h1>

<% if @song.album.present? %>
  <p>Album: <%= link_to @song.album.name, @song.album %></p>
<% end %>

<% unless @song.link.nil? || @song.link.empty? %>
  <iframe src="<%= @song.link %>" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
<% end %>

<div class="controls">
  <%= link_to "Edit Song", edit_song_path(@song) %>
  <%= link_to "Delete Song", @song, :method => "delete", :data => { :confirm => "Are you sure you want to delete this song?!" } %>
</div>